#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from html.parser import HTMLParser
from pathlib import Path


METADATA_KEYS = (
    "company",
    "role",
    "location",
    "date",
    "salutation",
    "recipient_name",
    "recipient_title",
    "closing",
    "signature",
)

KEY_PATTERN = "|".join(re.escape(key) for key in METADATA_KEYS)
METADATA_LABEL_RE = re.compile(rf"\b(?P<key>{KEY_PATTERN})\s*:", re.IGNORECASE)
GREETING_PREFIXES = (
    "dear ",
    "hello ",
    "hi ",
    "to whom it may concern",
)
SIGNOFF_LINE_RE = re.compile(
    r"^\s*(sincerely|best|best regards|regards|respectfully|kind regards|warm regards|yours truly)[,!:.;]?"
    r"(\s+[a-z][a-z .'\-]*)?\s*$",
    re.IGNORECASE,
)
DATE_LINE_RE = re.compile(
    r"^\s*("
    r"(january|february|march|april|may|june|july|august|september|october|november|december)\s+\d{1,2},\s+\d{4}"
    r"|\d{4}-\d{2}-\d{2}"
    r")\s*$",
    re.IGNORECASE,
)
HEADER_MARKERS = (
    "example candidate",
    "candidate@example.com",
    "555-010-1234",
    "linkedin.com/in/example-candidate",
    "example.com",
    "github.com/example-candidate",
)


class ValidationError(ValueError):
    """Raised when a cover letter input or rendered artifact fails validation."""


class _VisibleTextParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self._skip_depth = 0
        self._parts: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag.lower() in {"head", "script", "style", "noscript"}:
            self._skip_depth += 1

    def handle_endtag(self, tag: str) -> None:
        if tag.lower() in {"head", "script", "style", "noscript"} and self._skip_depth:
            self._skip_depth -= 1

    def handle_data(self, data: str) -> None:
        if self._skip_depth == 0 and data.strip():
            self._parts.append(data)

    def text(self) -> str:
        return "\n".join(self._parts)


def _line_snippet(line: str) -> str:
    normalized = " ".join(line.split())
    if len(normalized) > 120:
        return f"{normalized[:117]}..."
    return normalized


def _label_hits(text: str, *, start_line: int = 1) -> list[tuple[str, int, str]]:
    hits: list[tuple[str, int, str]] = []
    for offset, line in enumerate(text.splitlines(), start=start_line):
        for match in METADATA_LABEL_RE.finditer(line):
            hits.append((match.group("key").lower(), offset, _line_snippet(line)))
    return hits


def _raise_if_errors(errors: list[str]) -> None:
    if errors:
        raise ValidationError("\n".join(errors))


def html_to_visible_text(rendered_html: str) -> str:
    parser = _VisibleTextParser()
    parser.feed(rendered_html)
    return parser.text()


def validate_cover_letter_source_text(text: str, *, source: str = "<cover-letter-source>") -> None:
    lines = text.splitlines()
    errors: list[str] = []

    for key, line_number, snippet in _label_hits(text):
        errors.append(
            f"{source}:{line_number}: metadata labels are not allowed in body-only cover letter source: "
            f"{key}: ({snippet})"
        )

    non_empty_lines = [(index + 1, line.strip()) for index, line in enumerate(lines) if line.strip()]
    lower_lines = [(line_number, line.lower()) for line_number, line in non_empty_lines]

    if non_empty_lines:
        first_paragraph = next((part for part in re.split(r"\n\s*\n", text.strip()) if part.strip()), "")
        first_normalized = " ".join(first_paragraph.split()).lower()
        if first_normalized.startswith(GREETING_PREFIXES):
            errors.append(f"{source}:{non_empty_lines[0][0]}: greeting is generated by the template; remove it from the TXT body.")

    for line_number, lowered in lower_lines:
        if lowered in HEADER_MARKERS or any(marker in lowered for marker in HEADER_MARKERS[1:]):
            errors.append(f"{source}:{line_number}: header/contact information is generated by the template; remove it from the TXT body.")
        if SIGNOFF_LINE_RE.match(lowered):
            errors.append(f"{source}:{line_number}: closing/signature is generated by the template; remove it from the TXT body.")
        if DATE_LINE_RE.match(lowered):
            errors.append(f"{source}:{line_number}: date is generated by the template; remove it from the TXT body.")

    _raise_if_errors(errors)


def validate_cover_letter_source_path(path: Path) -> None:
    if not path.exists():
        raise ValidationError(f"{path}: file does not exist.")
    validate_cover_letter_source_text(path.read_text(encoding="utf-8"), source=str(path))


def validate_cover_letter_rendered_text(text: str, *, source: str = "<rendered-cover-letter>") -> None:
    errors = [
        f"{source}:{line_number}: metadata label leaked into rendered cover letter: {key}: ({snippet})"
        for key, line_number, snippet in _label_hits(text)
    ]
    _raise_if_errors(errors)


def validate_cover_letter_rendered_html(rendered_html: str, *, source: str = "<rendered-cover-letter-html>") -> None:
    validate_cover_letter_rendered_text(html_to_visible_text(rendered_html), source=source)


def _extract_pdf_text(path: Path) -> str:
    try:
        from pypdf import PdfReader  # type: ignore
    except ModuleNotFoundError:
        PdfReader = None  # type: ignore

    if PdfReader is not None:
        reader = PdfReader(str(path))
        return "\n".join(page.extract_text() or "" for page in reader.pages)

    try:
        from PyPDF2 import PdfReader as PyPdf2Reader  # type: ignore
    except ModuleNotFoundError:
        PyPdf2Reader = None  # type: ignore

    if PyPdf2Reader is not None:
        reader = PyPdf2Reader(str(path))
        return "\n".join(page.extract_text() or "" for page in reader.pages)

    pdftotext = shutil.which("pdftotext")
    if pdftotext:
        result = subprocess.run(
            [pdftotext, "-layout", str(path), "-"],
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout

    raise ValidationError(
        f"{path}: PDF text validation requires pypdf, PyPDF2, or the pdftotext command. "
        "Validate the rendered HTML or an extracted PDF text file instead."
    )


def validate_cover_letter_rendered_path(path: Path) -> None:
    if not path.exists():
        raise ValidationError(f"{path}: file does not exist.")

    if path.suffix.lower() in {".html", ".htm"}:
        validate_cover_letter_rendered_html(path.read_text(encoding="utf-8"), source=str(path))
        return

    if path.suffix.lower() == ".pdf" or path.read_bytes().startswith(b"%PDF"):
        validate_cover_letter_rendered_text(_extract_pdf_text(path), source=str(path))
        return

    validate_cover_letter_rendered_text(path.read_text(encoding="utf-8"), source=str(path))


def validate_cover_letter_path(path: Path, *, rendered: bool = False) -> None:
    if rendered or path.suffix.lower() in {".html", ".htm", ".pdf"}:
        validate_cover_letter_rendered_path(path)
    else:
        validate_cover_letter_source_path(path)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Validate body-only cover letter source text or rendered output for forbidden metadata/template text.",
    )
    parser.add_argument("paths", nargs="+", help="Cover letter TXT, rendered HTML, PDF text, or PDF path.")
    parser.add_argument(
        "--rendered",
        action="store_true",
        help="Treat text inputs as rendered output instead of body-only source TXT.",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    errors: list[str] = []

    for raw_path in args.paths:
        path = Path(raw_path).expanduser()
        try:
            validate_cover_letter_path(path, rendered=args.rendered)
        except ValidationError as exc:
            errors.append(str(exc))

    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    print("Cover letter validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
